version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: research_postgres
    environment:
      POSTGRES_DB: research_system
      POSTGRES_USER: research_user
      POSTGRES_PASSWORD: research_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - research_network

  redis:
    image: redis:7-alpine
    container_name: research_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - research_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: research_backend
    environment:
      - DATABASE_URL=postgresql://research_user:research_password@postgres:5432/research_system
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - research_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: research_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - research_network

  worker:
    build:
      context: ./workers
      dockerfile: Dockerfile
    container_name: research_worker
    environment:
      - DATABASE_URL=postgresql://research_user:research_password@postgres:5432/research_system
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./workers:/app
    networks:
      - research_network

volumes:
  postgres_data:
  redis_data:

networks:
  research_network:
    driver: bridge
